In [1]:
import pandas as pd
df_pais = pd.read_csv("./data/winemag-data-130k-v2.csv")

In [2]:
df_pais.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
df_pais.dtypes

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [3]:
import requests
import csv

#crearemos el diccionario paises para luego poder utilizarlo cuando creemos nuestra columna continente.

url = "https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv"
response = requests.get(url)
if response.status_code == 200:

    content = response.content.decode('utf-8').splitlines()
    
    paises = {}

    csv_reader = csv.reader(content)
    next(csv_reader)
    for row in csv_reader:
        pais = row[1]
        continente = row[6]
      
        paises[pais] = continente
        paises["US"]="América"

    print(paises)
else:
    print("No se pudo obtener el archivo CSV")

{'Afghanistan': 'Asia', 'US': 'América', 'Albania': 'Europa', 'Germany': 'Europa', 'Algeria': 'África', 'Andorra': 'Europa', 'Angola': 'África', 'Anguilla': 'América', 'Antarctica': 'Antártida', 'Antigua and Barbuda': 'América', 'Netherlands Antilles': 'América', 'Saudi Arabia': 'Asia', 'Argentina': 'América', 'Armenia': 'Asia', 'Aruba': 'América', 'Australia': 'Australia y Oceanía', 'Austria': 'Europa', 'Azerbaijan': 'Asia', 'Belgium': 'Europa', 'Bahamas': 'América', 'Bahrain': 'Asia', 'Bangladesh': 'Asia', 'Barbados': 'América', 'Belize': 'América', 'Benin': 'África', 'Bhutan': 'Asia', 'Belarus': 'Europa', 'Myanmar': 'Asia', 'Bolivia': 'América', 'Bosnia and Herzegovina': 'Europa', 'Botswana': 'África', 'Brazil': 'América', 'Brunei': 'Asia', 'Bulgaria': 'Europa', 'Burkina Faso': 'África', 'Burundi': 'África', 'Cape Verde': 'África', 'Cambodia': 'Asia', 'Cameroon': 'África', 'Canada': 'América', 'Chad': 'África', 'Chile': 'América', 'China': 'Asia', 'Cyprus': 'Asia', 'Vatican City State': 'Europa', 'Colombia': 'América', 'Comoros': 'África', 'Congo': 'África', 'North Korea': 'Asia', 'South Korea': 'Asia', 'Ivory Coast': 'África', 'Costa Rica': 'América', 'Croatia': 'Europa', 'Cuba': 'América', 'Denmark': 'Europa', 'Dominica': 'América', 'Ecuador': 'América', 'Egypt': 'África', 'El Salvador': 'América', 'United Arab Emirates': 'Asia', 'Eritrea': 'África', 'Slovakia': 'Europa', 'Slovenia': 'Europa', 'Spain': 'Europa', 'United States of America': 'América', 'Estonia': 'Europa', 'Ethiopia': 'África', 'Philippines': 'Asia', 'Finland': 'Europa', 'Fiji': 'Australia y Oceanía', 'France': 'Europa', 'Gabon': 'África', 'Gambia': 'África', 'Georgia': 'Asia', 'Ghana': 'África', 'Gibraltar': 'Europa', 'Grenada': 'América', 'Greece': 'Europa', 'Greenland': 'América', 'Guadeloupe': 'América', 'Guam': 'Australia y Oceanía', 'Guatemala': 'América', 'French Guiana': 'América', 'Guernsey': 'Europa', 'Guinea': 'África', 'Equatorial Guinea': 'África', 'Guinea-Bissau': 'África', 'Guyana': 'América', 'Haiti': 'América', 'Honduras': 'América', 'Hong Kong': 'Asia', 'Hungary': 'Europa', 'India': 'Asia', 'Indonesia': 'Asia', 'Iran': 'Asia', 'Iraq': 'Asia', 'Ireland': 'Europa', 'Bouvet Island': 'Antártida', 'Isle of Man': 'Europa', 'Christmas Island': 'Asia', 'Norfolk Island': 'Australia y Oceanía', 'Iceland': 'Europa', 'Bermuda Islands': 'América', 'Cayman Islands': 'América', 'Cocos (Keeling) Islands': 'Asia', 'Cook Islands': 'Australia y Oceanía', 'Åland Islands': 'Europa', 'Faroe Islands': 'Europa', 'South Georgia and the South Sandwich Islands': 'América', 'Heard Island and McDonald Islands': 'Antártida', 'Maldives': 'Asia', 'Falkland Islands (Malvinas)': 'América', 'Northern Mariana Islands': 'Australia y Oceanía', 'Marshall Islands': 'Australia y Oceanía', 'Pitcairn Islands': 'Australia y Oceanía', 'Solomon Islands': 'Australia y Oceanía', 'Turks and Caicos Islands': 'América', 'United States Minor Outlying Islands': '', 'Virgin Islands': 'América', 'United States Virgin Islands': 'América', 'Israel': 'Asia', 'Italy': 'Europa', 'Jamaica': 'América', 'Japan': 'Asia', 'Jersey': 'Europa', 'Jordan': 'Asia', 'Kazakhstan': 'Asia', 'Kenya': 'África', 'Kyrgyzstan': 'Asia', 'Kiribati': 'Australia y Oceanía', 'Kuwait': 'Asia', 'Lebanon': 'Asia', 'Laos': 'Asia', 'Lesotho': 'África', 'Latvia': 'Europa', 'Liberia': 'África', 'Libya': 'África', 'Liechtenstein': 'Europa', 'Lithuania': 'Europa', 'Luxembourg': 'Europa', 'Mexico': 'América', 'Monaco': 'Europa', 'Macao': 'Asia', 'Macedonia': 'Europa', 'Madagascar': 'África', 'Malaysia': 'Asia', 'Malawi': 'África', 'Mali': 'África', 'Malta': 'Europa', 'Morocco': 'África', 'Martinique': 'América', 'Mauritius': 'África', 'Mauritania': 'África', 'Mayotte': 'África', 'Estados Federados de': 'Australia y Oceanía', 'Moldova': 'Europa', 'Mongolia': 'Asia', 'Montenegro': 'Europa', 'Montserrat': 'América', 'Mozambique': 'África', 'Namibia': 'África', 'Nauru': 'Australia y Oceanía', 'Nepal': 'Asia', 'Nicaragua': 'América', 'Niger': 'África', 'Nigeria': 'África', 'Niue': 'Australia y Oceanía', 'Norway': 'Europa', 'New Caledonia': 'Australia y Oceanía', 'New Zealand': 'Australia y Oceanía', 'Oman': 'Asia', 'Netherlands': 'Europa', 'Pakistan': 'Asia', 'Palau': 'Australia y Oceanía', 'Palestine': 'Asia', 'Panama': 'América', 'Papua New Guinea': 'Australia y Oceanía', 'Paraguay': 'América', 'Peru': 'América', 'French Polynesia': 'Australia y Oceanía', 'Poland': 'Europa', 'Portugal': 'Europa', 'Puerto Rico': 'América', 'Qatar': 'Asia', 'United Kingdom': 'Europa', 'Central African Republic': 'África', 'Czech Republic': 'Europa', 'Dominican Republic': 'América', 'Réunion': 'África', 'Rwanda': 'África', 'Romania': 'Europa', 'Russia': 'Europa', 'Western Sahara': 'África', 'Samoa': 'Australia y Oceanía', 'American Samoa': 'Australia y Oceanía', 'Saint Barthélemy': 'América', 'Saint Kitts and Nevis': 'América', 'San Marino': 'Europa', 'Saint Martin (French part)': 'América', 'Saint Pierre and Miquelon': 'América', 'Saint Vincent and the Grenadines': 'América', 'Ascensión y Tristán de Acuña': 'África', 'Saint Lucia': 'América', 'Sao Tome and Principe': 'África', 'Senegal': 'África', 'Serbia': 'Europa', 'Seychelles': 'África', 'Sierra Leone': 'África', 'Singapore': 'Asia', 'Syria': 'Asia', 'Somalia': 'África', 'Sri Lanka': 'Asia', 'South Africa': 'África', 'Sudan': 'África', 'Sweden': 'Europa', 'Switzerland': 'Europa', 'Suriname': 'América', 'Svalbard and Jan Mayen': 'Europa', 'Swaziland': 'África', 'Tajikistan': 'Asia', 'Thailand': 'Asia', 'Taiwan': 'Asia', 'Tanzania': 'África', 'British Indian Ocean Territory': '', 'French Southern Territories': '', 'East Timor': 'Asia', 'Togo': 'África', 'Tokelau': 'Australia y Oceanía', 'Tonga': 'Australia y Oceanía', 'Trinidad and Tobago': 'América', 'Tunisia': 'África', 'Turkmenistan': 'Asia', 'Turkey': 'Asia', 'Tuvalu': 'Australia y Oceanía', 'Ukraine': 'Europa', 'Uganda': 'África', 'Uruguay': 'América', 'Uzbekistan': 'Asia', 'Vanuatu': 'Australia y Oceanía', 'Venezuela': 'América', 'Vietnam': 'Asia', 'Wallis and Futuna': 'Australia y Oceanía', 'Yemen': 'Asia', 'Djibouti': 'África', 'Zambia': 'África', 'Zimbabwe': 'África'}

In [4]:
#Realice al menos 4 renombre de columna.


df_pais = df_pais.rename(columns={
    'country': 'Pais',
    'description': 'Descripcion',
    'points': 'Puntos',
    'price': 'Precio'
})

#3 creación de nuevas columnas según criterio. Deberá crear las columnas que crea conveniente. Ejemplo: Según el país etiquetelos según continente.
df_pais['Continente'] = df_pais['Pais'].map(paises)
df_pais['Descuento'] = df_pais['Precio'] * 0.1 
df_pais['Precio_Final'] = df_pais['Precio'] - df_pais['Descuento'] 



df_pais.head(10)

,Unnamed: 0,Pais,Descripcion,designation,Puntos,Precio,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,Continente,Descuento,Precio_Final
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Europa,NaN,NaN
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Europa,1.5,13.5
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,América,1.4,12.6
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,América,1.3,11.7
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,América,6.5,58.5
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem,Europa,1.5,13.5
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo,Europa,1.6,14.4
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach,Europa,2.4,21.6
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel,Europa,1.2,10.8
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam,Europa,2.7,24.3

In [5]:
# reporte 01 mejores vinos puntuados por continente
try:
    idx = df_pais.groupby('Continente')['Puntos'].idxmax()
    reporte_mejores_vinos = df_pais.loc[idx, ['Continente', 'title', 'Puntos']]

    reporte_mejores_vinos = reporte_mejores_vinos.sort_values(by='Puntos', ascending=False)
    
except Exception as e:
    print(f"Error en generar el reporte de los continentes con los mejores vinos puntuados: {e}")
reporte_mejores_vinos.head()

,Continente,title,Puntos
45798,América,Cardinale 2006 Cabernet Sauvignon (Napa Valley),100
345,Australia y Oceanía,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,100
7335,Europa,Avignonesi 1995 Occhio di Pernice (Vin Santo ...,100
9912,África,De Toren 2014 Book 17 XVII Red (Stellenbosch),95
6673,Asia,Sula 2011 Dindori Reserve Shiraz (Nashik),93

In [15]:
#reporte 02 promedio de cada pais en puntos y en precio de cada vino
try:
    reporte02 = df_pais.groupby('Pais').agg({
        'Puntos': 'mean',
        'Precio': 'mean'
    }).sort_values(by='Puntos', ascending=False)
except Exception as e:
    print(f"Error en generar el reporte 1: {e}")
reporte02.head(20)

                 Puntos     Precio
Pais
England       91.250000  51.636364
India         90.750000  13.500000
Austria       89.992661  30.846774
Germany       89.808754  40.592233
Hungary       89.426230  50.819672
Canada        89.212963  35.575472
France        88.871487  41.577949
Morocco       88.636364  21.090909
Australia     88.582838  35.786701
Italy         88.566417  39.739836
US            88.556095  36.344889
Luxembourg    88.250000  23.000000
New Zealand   88.237381  26.662906
Turkey        88.232558  25.767442
Israel        88.189189  31.508065
Macedonia     88.166667  15.833333
Portugal      88.134323  25.647360
South Africa  88.074627  24.293478
Slovenia      87.974359  24.000000
Bulgaria      87.911765  14.014706

In [16]:
#reporte03 bodegas de vinos con los mejores promedios de puntuaciones
try:
     reporte03 = df_pais.groupby('winery').agg({'Puntos': 'mean'}).sort_values(by='Puntos', ascending=False)
       
except Exception as e:
        print(f"Error en generar el reporte 3: {e}")
reporte03.head(10)

                                  Puntos
winery
Cardinale                     100.000000
Clos de Tart                   98.000000
Araujo                         98.000000
Domaine des Lambrays           97.000000
Château Léoville Barton        96.666667
Château Pétrus                 96.666667
Tenuta dell'Ornellaia          96.285714
Salon                          96.000000
Harlan Estate                  96.000000
Mascarello Giuseppe e Figlio   96.000000

In [19]:
#reporte04 Promedio de puntos ,precio y cantidad de vinos por continente
try:
    reporte04 = df_pais.groupby('Continente').agg({
        'Puntos': 'mean',
        'Precio': 'mean',
        'title': 'count'
    }).rename(columns={'title': 'Cantidad_de_Vinos'}).sort_values(by='Puntos', ascending=False)

except Exception as e:
    print(f"Error en generar el reporte 4: {e}")
reporte04.head()

                        Puntos     Precio  Cantidad_de_Vinos
Continente
Europa               88.588346  36.720894              30822
Australia y Oceanía  88.450262  32.321907               1910
América              88.291979  34.446189              31581
Asia                 88.097297  28.885794                370
África               88.082888  24.239695                748

In [10]:
try:
    reporte03.to_excel('MejoresPuntuacionesMediasPorBodegas.xlsx', index=True)
except Exception as e:
    print(f"Error al guardar el reporte en Excel: {e}")